---
deployment:
  tasks:
    - export DEPLOYPATH=$HOME/public_html/
    - /bin/cp -R assets $DEPLOYPATH
    - /bin/cp default.html $DEPLOYPATH
    - /bin/cp pre-seed.html $DEPLOYPATH
    - /bin/cp devp.html $DEPLOYPATH
    - /bin/cp team.html $DEPLOYPATH
    - /bin/cp nelees-vision.html $DEPLOYPATH
    - /bin/cp nelees-one.html $DEPLOYPATH